# Generated by Django 5.2.14 on 2026-06-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='author',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='canonical_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='duration',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='embed_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='favicon_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='language',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='site_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='content_items', to='core.tag'),
        ),
    ]
