# Generated by Django 5.2.14 on 2026-06-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag_channel_cover_image_url_contentitem_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='channel_covers/'),
        ),
    ]
