# Generated by Django 5.2.14 on 2026-06-04 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contentitem_visibility_collection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItemVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('first_visited_at', models.DateTimeField(auto_now_add=True)),
                ('last_visited_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.contentitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_item_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_visited_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'item'), name='unique_content_item_visit')],
            },
        ),
    ]
