# Generated by Django 5.2.14 on 2026-06-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contentitemvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='expiry_amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='expiry_unit',
            field=models.CharField(blank=True, choices=[('years', 'Any'), ('months', 'Mes'), ('weeks', 'Setmana'), ('days', 'Dia'), ('hours', 'Hora'), ('minutes', 'Minut')], max_length=16),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='personal_comment',
            field=models.TextField(blank=True),
        ),
    ]
