# Generated by Django 5.2.14 on 2026-06-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contentitem_expiry_amount_contentitem_expiry_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='internal_context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta')], default='normal', max_length=16),
        ),
    ]
