# Generated by Django 5.2.15 on 2026-06-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contentitem_internal_context_contentitem_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='image_file',
            field=models.FileField(blank=True, upload_to='item_images/'),
        ),
    ]
