# Generated by Django 5.2.15 on 2026-06-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contentitemviewevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitemrating',
            name='main_value',
            field=models.CharField(choices=[('passo', 'Passo'), ('curios', 'Curiós'), ('val_la_pena', 'Val la pena'), ('recomanaria', 'Recomanaria'), ('must', 'Imprescindible')], max_length=24),
        ),
    ]
