# Generated by Django 5.2.15 on 2026-06-12 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_contentitemrating_main_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelTopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_items', to='core.channel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_top_entries', to='core.contentitem')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'position'), name='unique_channel_top_position'), models.UniqueConstraint(fields=('channel', 'item'), name='unique_channel_top_item')],
            },
        ),
    ]
