from django.urls import path, re_path

from .views import (
    ContentItemCreateView,
    ContentItemDeleteView,
    ContentItemDetailView,
    ContentItemUpdateView,
    ContentItemRatingView,
    ContentItemVisitToggleView,
    ContentItemVisitedView,
    ChannelUpdateView,
    DashboardView,
    ExploreView,
    HomeView,
    LegacyHtmlRedirectView,
    MagicLoginConfirmView,
    MagicLoginRequestView,
    MagicLoginSentView,
    PwaManifestView,
    PwaShareTargetView,
    PublicChannelView,
    PublicCollectionShareView,
    PublicItemShareView,
    PublicUserChannelShareView,
    ServiceWorkerView,
    TelegramWebhookView,
)


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("manifest.webmanifest", PwaManifestView.as_view(), name="pwa_manifest"),
    path("sw.js", ServiceWorkerView.as_view(), name="service_worker"),
    path("share/", PwaShareTargetView.as_view(), name="pwa_share_target"),
    path("explore/", ExploreView.as_view(), name="explore"),
    path("accounts/login/", MagicLoginRequestView.as_view(), name="login"),
    path("accounts/check-email/", MagicLoginSentView.as_view(), name="magic_login_sent"),
    path("accounts/magic/<str:token>/", MagicLoginConfirmView.as_view(), name="magic_login_confirm"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("dashboard/channel/", ChannelUpdateView.as_view(), name="channel_update"),
    path("items/new/", ContentItemCreateView.as_view(), name="contentitem_create"),
    path("items/<int:pk>/", ContentItemDetailView.as_view(), name="contentitem_detail"),
    path("items/<int:pk>/visited/", ContentItemVisitedView.as_view(), name="contentitem_visited"),
    path("items/<int:pk>/visit-toggle/", ContentItemVisitToggleView.as_view(), name="contentitem_visit_toggle"),
    path("items/<int:pk>/rating/", ContentItemRatingView.as_view(), name="contentitem_rating"),
    path("items/<int:pk>/edit/", ContentItemUpdateView.as_view(), name="contentitem_update"),
    path("items/<int:pk>/delete/", ContentItemDeleteView.as_view(), name="contentitem_delete"),
    path("public/i/<int:pk>/", PublicItemShareView.as_view(), name="public_item"),
    path("public/c/<int:pk>/", PublicCollectionShareView.as_view(), name="public_collection"),
    path("public/u/<int:pk>/", PublicUserChannelShareView.as_view(), name="public_user_channel"),
    path("integrations/telegram/webhook/", TelegramWebhookView.as_view(), name="telegram_webhook"),
    path("@<str:username>/", PublicChannelView.as_view(), name="public_channel"),
    re_path(r"^[\w-]+\.html$", LegacyHtmlRedirectView.as_view(), name="legacy_html_redirect"),
]
